### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [TyWR/Nord-zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

**Comment by tywr** [comment]
Just saw your message, I didn't have any notification so far...

I just updated the repo with a license, if you are still interested !
